version: '3.9'
services:
  db:
  # You can change it #
    image: postgres:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432" 
    volumes:
      - db-data:/var/lib/postgresql/data 
volumes:  
  db-data: